import type { PilotState, Activity } from './model.ts';
import { DEFAULT_TOWN } from './towns.ts';
export function createSeed(now = new Date()): PilotState {
  const at = (days: number, hour = 9) => {
    const d = new Date(now);
    d.setUTCDate(d.getUTCDate() + days);
    d.setUTCHours(hour - 8, 0, 0, 0);
    return d.toISOString();
  };
  const activity = (
    id: string,
    title: string,
    category: string,
    days: number,
    image: string | undefined,
    color: string,
    description: string,
    occupied: number,
    capacity: number,
  ): Activity => ({
    town: DEFAULT_TOWN,
    id,
    title,
    category,
    starts: at(days),
    ends: at(days, 11),
    image,
    color,
    description,
    occupied,
    capacity,
    location: 'Pek Kio Community Centre',
    deposit: 2,
    organizer: 'farah',
    status: days < 0 ? 'Completed' : 'Open',
    requirements: 'Open to adult residents. Beginners are very welcome.',
    safety:
      'An organizer will welcome you on arrival. Bring drinking water and let the team know about accessibility needs.',
    bonus: 0,
    interests: [],
  });
  const activities = [
    activity(
      'garden',
      'A little green, a lot of good',
      'Outdoors',
      7,
      '/images/community-garden.png',
      'green',
      'Get your hands in the soil with your neighbours. Learn to pot herbs, tend our shared planters, and take a little green home. All tools and seedlings are provided.',
      8,
      12,
    ),
    activity(
      'clay',
      'Clay, coffee & good company',
      'Arts & crafts',
      8,
      '/images/community-clay.png',
      'peach',
      'A slow morning making something with your hands. Shape a pinch pot, swap stories, and enjoy a cup of kopi. No pottery experience needed; materials are provided.',
      10,
      16,
    ),
    activity(
      'walk',
      'The Sunday neighbourhood walk',
      'Wellness',
      9,
      undefined,
      'blue',
      'Discover familiar streets through fresh eyes on an easy, step-free walk around Pek Kio. We will stop for a stretch and finish with a neighbourly chat.',
      6,
      15,
    ),
    activity(
      'digital',
      'Tech help, one neighbour at a time',
      'Learning',
      10,
      undefined,
      'yellow',
      'Bring your phone and your questions. Practise video calls, recognise suspicious messages, and learn a few useful everyday digital skills with patient neighbours.',
      12,
      12,
    ),
    activity(
      'study',
      'Neighbourhood study sprint',
      'Learning',
      -1,
      undefined,
      'blue',
      'A focused study session. Helpers prepared the room, welcomed participants, and supported small learning groups.',
      9,
      12,
    ),
    activity(
      'repair',
      'Repair café: give it a second life',
      'Interest groups',
      14,
      undefined,
      'peach',
      'Help shape a neighbourhood repair café. Express your interest and we will find a date when ten neighbours are ready to join.',
      0,
      15,
    ),
  ];
  activities[2].location = 'Farrer Park MRT · Exit D';
  activities[2].bonus = 5;
  activities[3].bonus = 5;
  activities[5].status = 'Proposed';
  activities[5].interests = [
    'sample-1',
    'sample-2',
    'sample-3',
    'sample-4',
    'sample-5',
    'sample-6',
  ];
  const old = Array.from({ length: 4 }, (_, i) =>
    activity(
      `past-${i}`,
      [
        'Community kitchen morning',
        'Books for every neighbour',
        'A greener Pek Kio',
        'Saturday learning circle',
      ][i],
      'Community',
      -7 + i,
      undefined,
      'green',
      'A completed sample community activity.',
      8,
      12,
    ),
  );
  return {
    town: DEFAULT_TOWN,
    version: 1,
    created: now.toISOString(),
    periodStart: at(-8),
    paused: false,
    activities: [...activities, ...old],
    registrations: [
      {
        id: 'reg-study',
        activityId: 'study',
        resident: 'mei',
        status: 'Attended',
        deposit: 0,
        created: at(-2),
        role: 'Helper',
      },
    ],
    contributions: [
      {
        id: 'claim-study',
        activityId: 'study',
        resident: 'mei',
        role: 'Helper',
        description:
          'I set up tables, welcomed nine neighbours, and helped two participants find learning resources. Farah confirmed my help on the attendance sheet.',
        evidence: [],
        status: 'Pending',
        created: at(-1, 12),
      },
      ...old.map((a, i) => ({
        id: `claim-past-${i}`,
        activityId: a.id,
        resident: 'mei',
        role: 'Helper' as const,
        description:
          'Verified help with setup and welcoming neighbours. Example contribution record.',
        evidence: [],
        status: 'Approved' as const,
        created: a.ends,
        reviewed: a.ends,
        reviewer: 'daniel',
        awarded: 10,
      })),
    ],
    rewards: [
      {
        id: 'kopi',
        title: 'Your next kopi is on us',
        partner: 'Pek Kio Kopi',
        pathway: 'Everyday',
        cost: 50,
        value: 5,
        boost: 0,
        stock: 24,
        simulated: false,
        description:
          'A S$5 voucher for coffee, tea, or a neighbourhood breakfast. Example merchant.',
        color: 'peach',
        extra: 0,
        merchant: 'pek-kio-kopi',
      },
      {
        id: 'materials',
        title: 'Make something your own',
        partner: 'Community workshop',
        pathway: 'Community',
        cost: 30,
        value: 3,
        boost: 0,
        stock: 16,
        simulated: false,
        description:
          'Materials for an approved community workshop. Starter or earned credits are welcome.',
        color: 'green',
        extra: 0,
        merchant: 'community',
      },
      {
        id: 'swim',
        title: 'A little time to move',
        partner: 'ActiveSG pathway',
        pathway: 'Sport & culture',
        cost: 100,
        value: 15,
        boost: 5,
        stock: 12,
        simulated: true,
        description:
          'Explore a sponsor-supported sport experience. No official credits are transferred and no real booking is made.',
        color: 'blue',
        extra: 0,
        merchant: 'partner',
      },
      {
        id: 'culture',
        title: 'Make room for a new perspective',
        partner: 'Culture Pass pathway',
        pathway: 'Sport & culture',
        cost: 100,
        value: 10,
        boost: 0,
        stock: 10,
        simulated: true,
        description:
          'Illustrates remaining-cost support for a cultural experience. Your official Culture Pass balance is never changed.',
        color: 'peach',
        extra: 0,
        merchant: 'partner',
      },
      {
        id: 'learn',
        title: 'Keep that curiosity growing',
        partner: 'Learning sponsorship pathway',
        pathway: 'Learning',
        cost: 100,
        value: 10,
        boost: 0,
        stock: 8,
        simulated: true,
        description:
          'A sample S$10 sponsorship toward a S$30 community course. Provider approval is required; this does not convert SkillsFuture credits.',
        color: 'yellow',
        extra: 20,
        merchant: 'partner',
      },
    ],
    vouchers: [],
    transactions: [
      {
        id: 'starter-issued',
        resident: 'mei',
        type: 'starter',
        creditType: 'starter',
        available: 50,
        reserved: 0,
        description: 'Welcome to the neighbourhood · starter credits',
        created: at(-8),
        reference: 'onboarding-mei',
      },
      ...old.map((a, i) => ({
        id: `earned-${i}`,
        resident: 'mei',
        type: 'earned' as const,
        creditType: 'earned' as const,
        available: 10,
        reserved: 0,
        description: `Helper · ${a.title}`,
        created: a.ends,
        reference: `claim-past-${i}`,
      })),
    ],
    grants: [],
    incidents: [],
    notices: [
      {
        id: 'welcome',
        text: 'Your study sprint contribution is waiting for independent review.',
        created: at(-1, 12),
      },
    ],
    processed: [],
  };
}
